### ISSUE TITLE
How to infer from the pretrained model?

### ISSUE THREAD

**Issue by smeaktrobush** [dair-iitd/imojie#1]
Hi, I'm trying to get predictions in Jupyter Notebook and I can't get around this error. Any help is appreciated!

ERROR:allennlp.data.vocabulary:Namespace: bert
ERROR:allennlp.data.vocabulary:Token: [unused99]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-e1bcaa81823b> in <module>
----> 1 predictor.predict_json({'source':'32.7 % of all households were made up of individuals and 15.7 % had someone living alone who was 65 years of age or older .'})

/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py in predict_json(self, inputs)
     63     def predict_json(self, inputs: JsonDict) -> JsonDict:
     64         instance = self._json_to_instance(inputs)
---> 65         return self.predict_instance(instance)
     66 
     67     def json_to_labeled_instances(self, inputs: JsonDict) -> List[Instance]:

/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py in predict_instance(self, instance)
    178 
    179     def predict_instance(self, instance: Instance) -> JsonDict:
--> 180         outputs = self._model.forward_on_instance(instance)
    181         return sanitize(outputs)
    182 

/usr/local/lib/python3.6/dist-packages/allennlp/models/model.py in forward_on_instance(self, instance)
    124         ``torch.Tensors`` into numpy arrays and remove the batch dimension.
    125         """
--> 126         return self.forward_on_instances([instance])[0]
    127 
    128     def forward_on_instances(self,

/usr/local/lib/python3.6/dist-packages/allennlp/models/model.py in forward_on_instances(self, instances)
    153             dataset.index_instances(self.vocab)
    154             model_input = util.move_to_device(dataset.as_tensor_dict(), cuda_device)
--> 155             outputs = self.decode(self(**model_input))
    156 
    157             instance_separated_output: List[Dict[str, numpy.ndarray]] = [{} for _ in dataset.instances]

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

/workdir/Desktop/rel/github/imojie/imojie/models/copy_seq2seq_bahdanu.py in forward(self, source_tokens, source_token_ids, source_to_target, metadata, target_tokens, target_token_ids, optimizer)
    380             # not built at __init__ function
    381             # so need to introduce another function
--> 382             self.initialize()
    383             self._initialized = True
    384 

/workdir/Desktop/rel/github/imojie/imojie/models/copy_seq2seq_bahdanu.py in initialize(self)
    260             self.vocab._oov_token = '[unused99]'
    261             self.vocab._padding_token = '[PAD]'
--> 262         self._oov_index = self.vocab.get_token_index(self.vocab._oov_token, self._target_namespace)  # pylint: disable=protected-access
    263         self._pad_index = self.vocab.get_token_index(self.vocab._padding_token, self._target_namespace)  # pylint: disable=protected-access
    264 

/usr/local/lib/python3.6/dist-packages/allennlp/data/vocabulary.py in get_token_index(self, token, namespace)
    635         else:
    636             try:
--> 637                 return self._token_to_index[namespace][self._oov_token]
    638             except KeyError:
    639                 logger.error('Namespace: %s', namespace)

KeyError: '[unused99]'

### This is what I've tried so far.

`dataset_reader = CopySeq2SeqNetDatasetReader('bert')`

`config_file = os.path.join("github","imojie","imojie","configs","imojie.json")`
`with open(config_file) as f:`
`   model_config = Params(json.load(f))`

`serialization_dir=os.path.join("github","imojie","models","imojie")`
`weights = os.path.join("github","imojie","models","imojie","model_state_epoch_7.th")`

`model = Model.load(config=model_config,serialization_dir=serialization_dir,weights_file=weights)`

`predictor = MemSeq2SeqPredictor(model=model,dataset_reader=dataset_reader)`
`predictor.predict_json({'source':'some text.'})`

**Comment by SaiKeshav** [comment]
Thank you for your interest in the project. Sorry, for the delay in response. I have pushed a new file to the repository, standalone.py

You can use that to run on individual examples. Run it using
```
python standalone.py
```
