### ISSUE TITLE
Requirements.txt issues

### ISSUE THREAD

**Issue by griff4692** [dair-iitd/imojie#2]
Hi -

I had to comment out the torch and sentencepiece lines to get it working.  For the latter, I get the error

`ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.85 (from -r requirements.txt (line 28)) (from versions: 0.0.0, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.9, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.83, 0.1.86, 0.1.90, 0.1.91, 0.1.92)
ERROR: No matching distribution found for sentencepiece==0.1.85 (from -r requirements.txt (line 28))
`

**Comment by griff4692** [comment]
Update: I downgraded from python 3.8 to python 3.6 and it works now :)

**Comment by SaiKeshav** [comment]
Thanks for reporting this! I will update the README with this point.
