### ISSUE TITLE
Question for baseline implementations

### ISSUE THREAD

**Issue by daviddongkc** [dair-iitd/imojie#6]
Hi Keshav,

I have run through your baselines: IMoJIE (on OpenIE-4 bootstrapping) and CopyAttn+BERT (on OpenIE-4 bootstrapping). I would like to know how to implement other baselines such as CopyAtten + LSTM, CopyAtten + LSTM + iterative memory? I modified the config file ‘lstm_a’ and ‘lstm_s’ respectively. The training works fine but the inference cannot work. 

Also may I know what is coverage and coverage + BERT model?

Thank you a lot,
Best regards,
KC

**Comment by SaiKeshav** [comment]
(Repeating the communication on email for benefit of others) I have pushed corrections to lstm_s.json and lstm_a.json which respectively implement CopyAttn + LSTM and CopyAttn + LSTM +iterative memory. Both training and inference should work now.

The coverage model is an implementation of the Logician OpenIE model (https://arxiv.org/abs/1904.12535) which uses coverage attention to ensure all source words are attended over the various timesteps of the decoder (leading to greater "coverage" at the decoder). It is not a complete re-implementation as the Logician model also uses some language-specific heuristics that we did not find particularly relevant for English.
